=== nyknghi/if-projet-xml/ProjetXML/src/grammaire/utilisateur.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lutilisateurs (utilisateur*)>
<!ELEMENT utilisateur (nom, coordonnee, hobby*)>
<!ATTLIST utilisateur id CDATA #REQUIRED 
					age CDATA #IMPLIED
					genre (homme | femme) #IMPLIED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT coordonnee (adresse+, mail?, telephone*)>
<!ELEMENT adresse (numero, (rue | avenue), code, ville)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT avenue (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT hobby (#PCDATA)>

=== nyknghi/if-projet-xml/ProjetXML/src/dataSources/utilisateur.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lutilisateurs SYSTEM "../grammaire/utilisateur.dtd" >
<lutilisateurs>
  <utilisateur age="20" genre="homme">
    <nom>Jean</nom>
    <coordonnee>
      <adresse>
        <rue>11 Rue Jacquemont</rue>
        <code>75017</code>
        <ville>Paris</ville>
      </adresse>
    </coordonnee>
    <hobby>Sport</hobby>
  </utilisateur>
  <utilisateur age="22" genre="femme">
    <nom>Alice</nom>
    <coordonnee>
      <adresse>
        <rue>2 bis Rue Washington</rue>
        <code>75008</code>
        <ville>Paris</ville>
      </adresse>
    </coordonnee>
    <hobby>Musique</hobby>
  </utilisateur>
</lutilisateurs>
